#!/usr/bin/env bash
# koe — Azure OpenAI (gpt-4o-transcribe) provisioning
#
# Creates a resource group, an Azure OpenAI account, and a gpt-4o-transcribe
# deployment in the CURRENTLY ACTIVE az subscription, then writes endpoint/key
# to .koe.env (gitignored).
#
# Usage:
#   az account show          # make sure this is YOUR subscription, not work
#   ./scripts/setup-azure.sh
#
# Override defaults via env:
#   KOE_RG KOE_LOCATION KOE_ACCOUNT KOE_DEPLOYMENT KOE_MODEL_VERSION KOE_CAPACITY
#
# Requires: az CLI logged in.
set -euo pipefail

RG="${KOE_RG:-koe-rg}"
LOCATION="${KOE_LOCATION:-eastus2}"
ACCOUNT="${KOE_ACCOUNT:-koe-tx-$(openssl rand -hex 4)}"
DEPLOYMENT="${KOE_DEPLOYMENT:-gpt-4o-transcribe}"
MODEL="gpt-4o-transcribe"
MODEL_VERSION="${KOE_MODEL_VERSION:-2025-03-20}"
CAPACITY="${KOE_CAPACITY:-1}"
API_VERSION="${KOE_API_VERSION:-2025-03-01-preview}"
ENV_OUT="${KOE_ENV_OUT:-.koe.env}"

echo "Subscription : $(az account show --query name -o tsv)"
echo "Resource grp : $RG ($LOCATION)"
echo "Account      : $ACCOUNT"
echo "Deployment   : $DEPLOYMENT ($MODEL $MODEL_VERSION, GlobalStandard x$CAPACITY)"
echo

az group create -n "$RG" -l "$LOCATION" -o none
echo "✓ resource group"

az cognitiveservices account create \
  -n "$ACCOUNT" -g "$RG" -l "$LOCATION" \
  --kind OpenAI --sku S0 \
  --custom-domain "$ACCOUNT" \
  --yes -o none
echo "✓ Azure OpenAI account"

az cognitiveservices account deployment create \
  -n "$ACCOUNT" -g "$RG" \
  --deployment-name "$DEPLOYMENT" \
  --model-name "$MODEL" \
  --model-version "$MODEL_VERSION" \
  --model-format OpenAI \
  --sku-name GlobalStandard --sku-capacity "$CAPACITY" -o none
echo "✓ gpt-4o-transcribe deployment"

ENDPOINT=$(az cognitiveservices account show -n "$ACCOUNT" -g "$RG" --query properties.endpoint -o tsv)
KEY=$(az cognitiveservices account keys list -n "$ACCOUNT" -g "$RG" --query key1 -o tsv)

cat > "$ENV_OUT" <<EOF
# koe Azure config — generated by setup-azure.sh. DO NOT COMMIT.
export KOE_ENDPOINT="${ENDPOINT%/}"
export KOE_DEPLOYMENT="$DEPLOYMENT"
export KOE_API_VERSION="$API_VERSION"
export KOE_API_KEY="$KEY"
EOF

echo
echo "✓ wrote $ENV_OUT"
echo "  endpoint   : ${ENDPOINT%/}"
echo "  deployment : $DEPLOYMENT"
echo "  key        : ${KEY:0:6}…(hidden)"
echo
echo "Next: source $ENV_OUT && ./scripts/smoke-test.sh"
